### ISSUE TITLE
Sample Issue

### ISSUE THREAD

**Issue by nhmathis** [IBM-UrbanCode/PluginTemplate#1]
This is a sample Issue for Plugin-Template-UCD.

**Comment by vp415** [comment]
I am new to groovy and udeploy plugin. Can anybody tell me simple helloworld example using groovy in udeploy. I need to print helloworld along with name that is taken from PLUGIN_INPUT_PROPS and print it using output prop

**Comment by nhmathis** [comment]
Hi @shonayo,

This repository is exactly what you are looking for! Please download, clone, or fork the repo locally and follow these instructions to build your own simple plugin: https://developer.ibm.com/urbancode/docs/urbancode-plug-development-tutorial/

These instructions revolve largely around how an IBM UrbanCode Deploy plugin is structured and its various components. 

As for the Groovy programming language, there are many  examples, tutorials, and documents online. Too many to list. I would suggest running through our quick tutorial and then dive into some Groovy examples. Fortunately, plugins are not limited to the Groovy language. Many other plugins, such as the [Node.js plugin](https://github.com/IBM-UrbanCode/Node.js-UCD), take advantage of Shell. Any language that you can run on the command line, you can run through the plugin.xml's `<command>` section. 

If you have any additional questions about plugin development, please create a dwAnswer question here: https://developer.ibm.com/answers/questions/ask.html
Make sure you set the `UCDev` tag.

Regards,
Nick

**Comment by vp415** [comment]
@nhmathis Thanks for responding. Yeah I downloaded 3 xmlfiles and groovy helloworld script from repo. When I loaded it in automation plugin in udeploy, it successfully got loaded as well. But then it is not able to decode CommandHelper and AirPluginTool. I am getting error on these two. May be it is written for Anthill that's why? I am using it for udeploy

**Comment by vp415** [comment]
@nhmathis Below is the error I am getting :-

 org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/apps/uDeploy/agent4/var/plugins/com.urbancode.air.plugin.helloworld_1_9652690aa92c00ec349800d5970260c0154b1670c8454ff54da6b9808db2e306/helloworld.groovy: 1: unable to resolve class com.urbancode.air.AirPluginTool
 @ line 1, column 1.
   import com.urbancode.air.AirPluginTool; 
   ^

/apps/uDeploy/agent4/var/plugins/com.urbancode.air.plugin.helloworld_1_9652690aa92c00ec349800d5970260c0154b1670c8454ff54da6b9808db2e306/helloworld.groovy: 2: unable to resolve class com.urbancode.air.CommandHelper
 @ line 2, column 1.
   import com.urbancode.air.CommandHelper;

**Comment by nhmathis** [comment]
Hi @shonayo,

This error indicates that the groovy-plugin-utils jar file isn't located on the classpath. Were you able to follow this tutorial? https://developer.ibm.com/urbancode/docs/urbancode-plug-development-tutorial/ 

If I could guess, it sounds like you downloaded the files individually rather than downloading or cloning the entire repository. The other files, specifically the `build.gradle` file, contain important code to package the plugin into a workable zip. This build code will simultaneously download and then place the groovy-plugin-utils library in the correct directory for run time. 

Follow the above step by step guide to build the plugin and get it running! If you are confused on any sections of the tutorial, please submit a [question on dwAnswers](https://developer.ibm.com/answers/questions/ask.html) with the `UCDev` tag. 

If you have any trouble building the plugin itself, in this case running the `gradle` command, the build documentation should have answers: https://developer.ibm.com/urbancode/docs/plug-in-build-requirements/

Nick

**Comment by vp415** [comment]
@nhmathis :The tutorial doesn't actually explains where to edit my code and where to build, since I am new to udeploy and groovy I am finding it difficult to understand the context. I downloaded/cloned the repository and imported it directly to udeploy under automation plugin, while doing so I got an error that the plugin.xml is not present in its root directory of zip file. Can you please assist with clear steps as where to edit the files once downloaded? Why is command line in picture? how do I go to ucd template folder in command line.

**Comment by nhmathis** [comment]
@shonayo 

Thank you for your feedback on the tutorial! I've made a few updates that will hopefully make it more complete. As for your issues...

You've confirmed my suspicion that the plugin distributable was not installed correctly. By the looks of your error, it would indicate that you installed the project's root folder instead of the .zip. To build the plugin you must run the `gradle` command on the command line in the root directory of the plugin project. (This is the same folder as the `build.gradle` file.) The `gradle` command will build the plugin and create the zip file in the `build/distributions` directory.  You do not need to make any changes to the initial project to build a workable plugin. The built package will be called `<name>-1.dev.zip`. UrbanCode Deploy is expects this .zip file, not the project repository folder.

Note: You must install Gradle locally to run the `gradle` command. The build documentation linked in a above comment details this process. 

Simplified Steps:
1) Ensure Gradle is installed. Follow the build documentation above if necessary.
2) From a terminal, go to the root directory of the plugin's directory, and run `gradle`. 
3) Next, go into `build/distributions` folder. (This does not need to be done on the command line.) You should find a .zip file.  If this file doesn't exist, then the plugin did not build. Review the `gradle` command line's output and fix the errors or re-clone/re-download the plugin repository again and try to build again.
4) Once built successfully, take the .zip file and install the plugin through UCD's GUI. Here is a sample plugin of what a built plugin zip may look like. 
[helloworld-2.dev.zip](https://github.com/IBM-UrbanCode/Plugin-Template-UCD/files/559005/helloworld-2.dev.zip)
5) Create a Process or Component Process and run the "Hello World" step.

Finally, I strongly suggest additional research is done in basic command line use, Groovy development, and UrbanCode Deploy. There are plenty of videos, documents, and blogs that can give a much better explanation of these topics than I can in a single GitHub comment. While we've tried to make this tutorial simple, we do assume a basic level of programming knowledge. It's a long path, but this basis is crucial in both plugin and software development.

Good luck!

Nick

**Comment by Srikanthv2303** [comment]
@nhmathis , I am trying to create a plugin using eclipse for IBM Urban Code deploy. I get the below error while I upload the zip file of plugin to UCD. can you please help ?

"The file plugin.xml was not found within the root directory of the zip file"

**Comment by nhmathis** [comment]
@Srikanthv2303,

Zipping up the source code will not work, it requires a certain structure. Running the `ant` or `gradle` command (depending on the build type) will construct the .zip with the correct structure. Also, extracting any install-able zip will show the proper folder/file structure.
